name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: just check
